apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: booking-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

