# Use an official OpenJDK runtime as a parent image
FROM openjdk:17

# Set the working directory to /app
WORKDIR /wallet

# Copy the current directory contents into the container at /wallet
COPY . .

# Install Maven
RUN microdnf install -y maven

# Build the projects with Maven
RUN mvn install

ENTRYPOINT ["java" ,"-jar","target/wallet-0.0.1-SNAPSHOT.jar"]
